# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Full name')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_verifed', models.BooleanField(default=False)),
                ('email_verify_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.IntegerField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'student')], default=3)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('blocked', models.BooleanField(default=False, verbose_name='blocked')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date of joining')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
