# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(unique=True)),
                ('token', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='role',
            field=models.IntegerField(choices=[(2, 'teacher'), (1, 'admin'), (3, 'student')], default=3),
        ),
    ]
