# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171008_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='role',
            field=models.IntegerField(choices=[(3, 'student'), (2, 'teacher'), (1, 'admin')], default=3),
        ),
    ]
