# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20171008_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date and time of edit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TaskUser', verbose_name='Task created by')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TaskAssignUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('disapproved', 'Disapproved'), ('approved', 'Approved'), ('to-do', 'To-Do'), ('done', 'Done'), ('doing', 'Doing')], default='to-do', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date and time of edit')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Task', verbose_name='Task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TaskUser', verbose_name='Assign user')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
