# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignuser',
            name='status',
            field=models.CharField(choices=[('disapproved', 'Disapproved'), ('done', 'Done'), ('approved', 'Approved'), ('doing', 'Doing'), ('to-do', 'To-Do')], default='to-do', max_length=20),
        ),
    ]
